CREATE TABLE orders (
    order_id           VARCHAR(10) PRIMARY KEY,
    customer_id        VARCHAR(10),
    product_id         VARCHAR(10),
    order_date         DATE,
    ship_date          DATE,
    quantity           INT,
    unit_price         NUMERIC(10,2),
    discount_percent   NUMERIC(5,2),
    shipping_cost      NUMERIC(10,2),
    total_amount       NUMERIC(12,2),
    payment_method     VARCHAR(30),
    order_status       VARCHAR(20),
    region             VARCHAR(20),
    sales_channel      VARCHAR(20),
    return_flag        VARCHAR(5),
    gross_amount       NUMERIC(12,2),
    net_amount         NUMERIC(12,2),
    lost_amount        NUMERIC(12,2),
    cost_price         NUMERIC(10,2),
    total_cost         NUMERIC(12,2),
    profit             NUMERIC(12,2),
    profit_margin_pct  NUMERIC(6,2),
	 FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
 	FOREIGN KEY (product_id) REFERENCES products(product_id),
     FOREIGN KEY (order_date) REFERENCES date_dimension(date)
);